image:
  file: Dockerfile
# exposed ports
ports:
- port: 8080
  onOpen: open-preview
# start up tasks
tasks:
- init: echo hello && fail
  command: ./mvnw package -DskipTests # FIXME : LS removes *.css on initialize
