#######################
# Aurea Central Jervis Example
#######################
# User guide and documentation can be found at: https://github.com/trilogy-group/aurea-central-jervis-example
# This project is based on https://github.com/aurea-central-jervis-example/aurea-central-jervis

language: java

git:
  submodules: true
    

env:
  global:
    - DOCKER_IMAGE_BASE_URL=registry2.swarm.devfactory.com/aurea/central/jervis/petclinic
    - DOCKER_HOST=tcp://dlb1.aureacentral.com:2375

cache:
  directories:
    - ${HOME}/.m2

before_install: 'ls -l aurea-central-jervis'

jenkins:
  collect:
    collect:

inventories:
  dev: 
    - ../../inventories/dev
  regression: 
    - ../../inventories/regression
  qa: 
    - ../../inventories/qa
  staging: 
    - ../../inventories/staging
  release: 
    - ../../inventories/release
