language: java
script: mvn package -Popenshift
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
deploy:
  provider: openshift
  user: "aditya.vadaganadam@gmail.com"
  password: "peanut45" # can be encrypted
  domain: "101devops"
  app: "forumapp"
