language: java
script: mvn package -Popenshift
jdk:
  - oraclejdk7
  - openjdk7
deploy:
  provider: openshift
  user: "aditya.vadaganadam@gmail.com"
  password: "" # can be encrypted
  domain: "101devops"
  app: "forumapp"
