language: java
sudo: true
dist: trusty

# use Java 9
jdk: oraclejdk9

before_install:
  - chmod +x mvnw

jobs:
  include:
    - stage: javaformat
      script: ./mvnw clean spring-javaformat:apply
    - stage: test
      script: ./mvnw test
    - stage: verify
      script: ./mvnw verify
    - stage: sonar
      script: ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

cache:
  directories:
    - $HOME/.m2

notifications:
  email: pedsf.fullstack@gmail.com
