dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
- chmod +x mvnw
- mysql -e 'CREATE DATABASE cheapy;'
- sudo apt-get update
script:
  - mvn test -Dspring.profiles.active=mysql-travis

