language: java
sudo: false
install: true

addons:
  sonarqube:
    organization: "ihristovut-github"
    token:
      secure: SONAR_TOKEN

jdk: oraclejdk8

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
