---
pool: 
  name: ubuntu-latest
trigger:
  - main
jobs:
  - job:
    steps:    
      - script: sudo apt update
      - script: sudo apt install maven -y
      - script: sudo apt install git -y

  - job: package
    displayName: build the package
    steps:
      - task: Maven@3
        inputs:
          mavenPOMFile: 'pom.xml'
          publishJUnitResults: true
          goals: 'package'
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          jdkVersionOption: '1.17'
          mavenDirectory: spring-petclinic
