trigger:
- master
- releases/*


# All tasks on Linux

- job: build all linux
  displayName: Build all tasks (Linux)
  condition: and(succeeded(), not(variables.task), eq(variables.os, 'Linux'))
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: ci/build-all-steps.yml
    parameters:
      os: Linux
