pool:
  name: "Azure Pipelines"
trigger:
  - main
jobs:
  - job: myjob
    displayName: myjob
    steps:
     - task: Maven@3
       inputs:
         mavenPOMFile: 'pom.xml'
         publishJUnitResults: true
         goals: 'package'
         testResultsFiles: '**/surefire-reports/TEST-*.xml'
         javaHomeOption: 'Path'
         jdkDirectory: /usr/lib/jvm/java-17-openjdk-amd64
         mavenVersionOption: 'path'
         mavenDirectory: /home/ubuntu/spring-petclinic
     - task: PublishBuildArtifacts@1
       inputs:
         PathtoPublish: '$(Build.Repository.LocalPath)' 
         ArtifactName: 'drop' 
         publishLocation: 'Container'    
     - task: DownloadPipelineArtifact@2
       inputs:
         buildType: 'current'
         downloadType: 'single'
         artifactName: 'drop'
         targetPath: '/home/ubuntu/build'
     - script: ansible-playbook -i host ansibleplaybook.yaml    

