pool: "Azure Pipelines"
trigger:
  - main
jobs:
  - job: "gradle"
    displayName: "gradle job"
    steps:
      - task: "Gradle@3"
        inputs:
          
          gradleWrapperFile: 'gradlew'
          tasks: 'build'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
        