---
pool:
  name: default
trigger:
  - main
steps:
  - task: Maven@3
    inputs:
      mavenPOMFile: 'pom.xml'
      publishJUnitResults: true
      goals: 'package'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkDirectory: /usr/lib/jvm/java-17-openjdk-amd64
      mavenVersionOption: 'path'
      mavenDirectory: /home/ubuntu/spring-petclinic
  - script: aws s3 cp '$(Build.Repository.localPath)/target' s3://spcfeb18 --grants read=uri=https://acs.amazonaws.com/groups/global/AllUsers --recursive
