# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  imageRepo: pet
  tag: '$(Build.BuildId)'

steps:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: myagentpool
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'viktorponomarov'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: 'Docker/Dockerfile'
        tags: |
          $(tag)




