# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: myagentpool
      
variables:
  imageRepo: 'viktorponomarov/pet'
  tag: '$(Build.BuildId)'

stages:
- stage: Info
  displayName: Collect information
  jobs:
  - job: GetInfo
    displayName: Get info about system
    steps:
      - script: |
          pwd
          w   
          ls -l
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Cred to Docker Hub'
        repository: 'pet'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'
          




