# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.SourceBranchName)'

stages:
- stage: BuildAndPush
  displayName: 'Build container image and push to docker hub'
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: 'echo $(Build.SourceBranchName)' 
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
        containerRegistry: docker-robinwyss
        repository: robinwyss/petclinic-l4j