---
version: 0.2
phases:
  install:
    runtimeversion: java:corretto17
  pre_build:
    commands:
      - echo Nothing to do in prebuild
  build:
    commands:
      - echo Build Started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/spring-petckinic-2.2.0.BUILD-SNAPSHOT.jar
...