---

- hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/deploy/{{ wimpy_deployment_environment }}.yml"
  vars:
    wimpy_project: "spring-petclinic"
    wimpy_app_port: 8080
    wimpy_needs_elb: True
    wimpy_app:
      pre_commands:
        - "/usr/bin/sh -c '/usr/bin/$(/usr/bin/docker run --rm xueshanf/awscli aws ecr get-login --region {{ wimpy_aws_region }} --registry-ids={{ registry_aws_account }})'"
  roles:
    - role: fiunchinho.wimpy
