mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=petclinic
    - MYSQL_PASSWORD=petclinic
    - MYSQL_DATABASE=petclinic
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:latest-jdk8
    privileged: true
    user: admin
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
