version: "2.2"

services:
  spring-petclinic:
    build: ./
    ports:
      - "8080:8080"
    environment:
      - DB="--spring.profiles.active=postgres"
  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
