---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: repicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        app: spc
    spc:
      containers:
        - name: spc
          image: shri1991/spring

---
apiVersion: v1
kind: Service
metadata:
  name: service-example
spec:
  ports:
    - name: http
      port: 80
      targetport: 80
  selector:
    app: spc
