apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  resources:
    requests:
      storage: 256Mi
  accessModes:
    - ReadWriteOnce

---

apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:15.2
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_DB
              value: "petclinic"
            - name: POSTGRES_USER
              value: "petclinic"
            - name: POSTGRES_PASSWORD
              value: "petclinic"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /data/db
          imagePullPolicy: Always
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgresql-pvc
