# database init, supports mysql too
database: h2
spring:
  datasource:
    schema: classpath*:db/${database}/schema.sql
    data: classpath*:db/${database}/data.sql
  jpa:
    hibernate.ddl-auto: none
    open-in-view: false
spring.thymeleaf.mode: HTML

# Internationalization
spring.messages.basename: messages/messages

# Actuator
management.endpoints.web.exposure.include: '*'

# Logging
logging.level.org.springframework: INFO
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE

# Maximum time static resources should be cached
spring.resources.cache.cachecontrol.max-age: 12h
