kind: Service
apiVersion: v1
metadata:
  name: pet-clinic
  namespace: staging
  labels:
    version: pc-8353ba1
spec:
  selector:
    app: auth-service
    version: pc-8353ba1
  ports:
    - port: 80
      targetPort: 8080
