kind: Service
apiVersion: v1
metadata:
  name: pet-clinic
  namespace: staging
  labels:
    version: master-507549c
spec:
  selector:
    app: auth-service
    version: master-507549c
  ports:
    - port: 80
      targetPort: 8080
