version: 2.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
            - v1-dependencies- # fallback in case previous cache key is not found

      - run: ./mvnw package
      - run: pwd; ls

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # - store_artifacts:
      #     path: /home/circleci/project/target/*.jar
        
      - run: ls /home/circleci/project/target/

      # - run:
      #     name: Save test results
      #     command: |
      #       mkdir -p ~/test-results/junit/
      #       find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
      #     when: always
      # - store_test_results:
      #     path: ~/test-results

      - store_test_results:  
          path: target/surefire-reports

      - store_artifacts:
          path: target/spring-petclinic-v1.jar      
      # - persist_to_workspace:
      #    root: ./
      #    paths:
      #      - target/

  test:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: ./mvnw test

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build
