---

- hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/{{ wimpy_deployment_environment }}.yml"
  vars:
    wimpy_project_name: "spring-petclinic"
    wimpy_docker_image_name: "fiunchinho/spring-petclinic"
    wimpy_app_port: 8080
    wimpy_deploy_strategy: "new_asg"
    wimpy_aws_elb_scheme: "internet-facing"
    wimpy_aws_elb_healthcheck:
      ping_protocol: "http"
      ping_port: 8080
      ping_path: "/"
      response_timeout: 5
      interval: 7
      unhealthy_threshold: 2
      healthy_threshold: 3
  roles:
    - role: wimpy.build
    - role: wimpy.deploy
