---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component.name }}-ui
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.component.external.ip }}
  selector:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.component.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.component.external.port }}
      targetPort: 8080
      name: ui

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component.name }}-discovery
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.component.external.ip }}
  selector:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.component.name }}
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
      name: slaves
