---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.component.name }}-pv
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.component.name }}
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: {{ .Values.component.volume.name }}
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.component.name }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 15Gi
  selector:
     matchLabels:
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      component: {{ .Values.component.name }}
