---
- name: Docker push
  hosts: agent-1
  become: yes

  tasks:
    - name: Install python3
      apt:
        name: python3-pip
        state: present

    - name: docker-py
      pip:
        name: docker-py
        state: absent

    - name: install docker pip
      pip:
        name: docker
        state: present

    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Setting mode for docker.sock
      shell: sudo chmod 666 /var/run/docker.sock

    - name: Docker service started
      service:
        name: docker
        state: started

    - name: Docker prune
      docker_container:
        name: spring-petclinic
        state: absent

    - name: Start the container
      docker_container:
        name: spring-petclinic
        image: "owlleg68/spring-petclinic:latest"
        state: started
        published_ports:
          - 0.0.0.0:8082:8080
