---
- name: Setup dev-tools instance
  hosts: dev-tools
  become: yes


  tasks:
       #=========Git===========
    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: yes

      #============Java======
    - name: Install Java-8
      apt:
        name: openjdk-8-jdk
        state: present

      #============Maven========
    - name: Install Maven
      apt:
        name: maven
        state: present

      #=======Jenkins=======
    - name: Wget url
      shell: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -

    - name: Adding to list
      shell: sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Start jenkins
      service:
       name: jenkins
       state: started

    - name: init password jenkin
      shell: sudo cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: print init password jenkins
      debug:
       var: result.stdout


