- hosts: east
  become: true
  tasks:
    - name: copy files
      copy:
        src: /var/lib/jenkins/workspace/Ansible-Freestyle/ansible/
        dest: /tmp
  
    - name: docker build 
      shell: docker-compose -f /tmp/docker-compose.yml build

    - name: docker down 
      shell: docker-compose -f /tmp/docker-compose.yml down

    - name: docker up 
      shell: docker-compose -f /tmp/docker-compose.yml up -d
