kind: Service
apiVersion: v1
metadata:
  name: pet-clinic
  namespace: production
  labels:
    version: v0.0.0
spec:
  selector:
    app: auth-service
    version: v0.0.0
  ports:
    - port: 80
      targetPort: 8080
