name: Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests with Maven
        run: mvn test

      # Store build artifacts for history
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: /spring-petclinic/reports/history/

      # Static Code Analysis with Checkstyle
      - name: Static Code Analysis with Checkstyle
        run: |
          # Install and run Checkstyle
          mvn org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle

          # Run Checkstyle
          mvn checkstyle:check

      # Store static code analysis reports
      - name: Archive Static Code Analysis Reports
        uses: actions/upload-artifact@v2
        with:
          name: static-code-analysis-reports
          path: /spring-petclinic/reports/checkstyle/

      # Code Coverage
      - name: Code Coverage
        run: |
          # Run JaCoCo report generation
            mvn jacoco:report

      # Store code coverage reports
      - name: Archive Code Coverage Reports
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-reports
          path: /spring-petclinic/reports/jacoco/
