name: Build and Publish Docker Image

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: |
          mvn -B clean package --file pom.xml
          echo "::set-output name=APP_VERSION::$(mvn --file pom.xml -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)"
        id: build-version
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: spring-petclinic-jar
          path: target/*.jar
      - name: Save version
        uses: noobly314/share-data@v1
        with:
          share-id: app_version
          mode: set
          key: version
          value: ${{ steps.build-version.outputs.APP_VERSION }}

  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Get Version
        id: get-version
        uses: noobly314/share-data@v1
        with:
          share-id: app_version
          mode: get
          key: version
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: spring-petclinic-jar
          path: target
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Docker Build Version DEV
        run: docker build -t allanweber/spring-petclinic:${{ steps.get-version.outputs.data }} -f docker/Dockerfile .
      - name: Build and Push Version
        run: docker push allanweber/spring-petclinic:${{ steps.get-version.outputs.data }}
      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: spring-petclinic-jar
