name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
          
      - name: Dump Context
        env: 
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      
      - run: echo "This is the payload ref ${{ github.event.client_payload.ref }}"
      - run: echo "sha from first run sha ${{ github.sha }}"  
      - run: echo "client payload sha ${{ github.event.client_payload.sha }}"
      
      #- run: echo ${{ github.event.client_payload.test }}
      #- run: echo ${{ github.event.client_payload.sha }}
      #- run: echo ${{ github.event.client_payload.test }}
