name: Test

on:
  workflow_call
  #- push

jobs:
  preflight-job:
    name: First Step
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        run: |
          curl \
          -H "Authorization: token :token" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/:user/:repo/dispatches" \
          -d '{
            "event_type": "awesomeness", 
            "client_payload": {"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "test": "test message"}}'

#         uses: peter-evans/repository-dispatch@v1
#         with:
#           token: ${{ secrets.MY_PAT }}
#           event-type: my-event
#           client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "test": "test message"}'
