name: Docker Image CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        ./mvnw package
        docker build . -f Dockerfile -t spring-petclinic
        git config --global user.email "67474440+Acibeee@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit -am "Automatic commit"
        git push
