name: Docker Image CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        ./mvnw package
        docker build . -f Dockerfile -t spring-petclinic
  push:
    needs: build
    runs-on: ubuntu-latest
    steps: 
    - name: Push to repo
      run: |
        git remote set-url origin git@github.com:Acibeee/spring-petclinic
        git config --global user.email "acibeee@gmail.com"
        git config --global user.name "Acibeee"
        git add .
        git commit -am "Automatic commit"
        git push
      
