name: Docker Image CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create jar file
      run: ./mvnw package
    - uses: mr-smithers-excellent/docker-build-push@v5
    - name: Build & push Docker image
      with:
        image: acidbees/spring-petclinic
        tags: v1, latest
        registry: registry-url.io
        dockerfile: Dockerfile.ci
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
