name: Docker Image CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        ./mvnw package
        docker build . -f Dockerfile -t spring-petclinic
  compose:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker environment
      run: |
        docker run -d -p 5000:5000 registry:2.7.1
        docker-compose up -d
        curl -f -I http://localhost:8080/ || exit 1
    needs: build
    
