# This is a basic workflow to help you get started with Actions

name: FirstPipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_second_job:
      name: Build call
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      # if: ${{ success() }}
      - uses: ./.github/workflows/build.yml