name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Setup GCP Service Account
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    - name: Docker Build
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/helloworld:$GITHUB_SHA .

    - name: Docker Push
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/helloworld:$GITHUB_SHA

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: YevheniiPokhvalii/spring-petclinic-gitops-test
        event-type: kubernetes-event
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

    - name: test run
      run: |
        echo ${{ github.event.client_payload.sha }}


