# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build-and-test

on: 
 push:
  branches: main
 pull_request:

jobs:
  build-and-test-matrix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 8, 11, 15 ]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
       path: ~/.m2/repository
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
        ${{ runner.os }}-maven-
    - name: Setup Java and Build
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}
    - run: mvn -B install --no-transfer-progress --file pom.xml
      
  build-image-and-publish:
    runs-on: ubuntu-latest
    needs: [build-and-test-matrix]
    env:
      USERNAME: 'omearaj'
      IMG_NAME: 'spring-petclinic'
      REGISTRY: 'ghcr.io'
      BUILDER: 'paketobuildpacks/builder:base'
      IMAGE_NAME: 'ghrc.io/omearaj/spring-petclinic'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
       path: ~/.m2/repository
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
        ${{ runner.os }}-maven-
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
   
    - uses: andrioid/setup-pack@v1.0.1
   
    - name: "😆 Image using Pack"
      run: |
        pack build ghcr.io/octodemo/spring-petclinic/spring-petclinic --builder paketobuildpacks/builder:base --env 'BP_JVM_VERSION=8.*' --publish
