name: Build Petclinic
on: [ push ]
jobs:
  Build-Petclinic:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v2        
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: echo "Hello Github Actions"
      - run: find
      - run: ./mvnw compile
  Test-Petclinic:
    runs-on: ubuntu-latest
    needs: [ Build-Petclinic ]
    steps:
      - run: find