name: Build Petclinic
on: [ push ]
jobs:
  Build-Petclinic:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v2        
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: ./mvnw compile
      - uses: actions/upload-artifact@v2
        with:
          name: petclinic-build
          path: target/

  Test-Petclinic:
    runs-on: ubuntu-latest
    needs: [ Build-Petclinic ]
    steps:
      - name: Check out repo code
        uses: actions/checkout@v2        
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/download-artifact@v2
        with:
          name: petclinic-build
          path: target/
      - run: mvn test

  Dockerize-Petclinic:
    runs-on: ubuntu-latest
    needs: [ Build-Petclinic ]
    steps:
      - name: Check out repo code
        uses: actions/checkout@v2        
      - uses: actions/download-artifact@v2
        with:
          name: petclinic-build
          path: target/
      - run: find
      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: my_container:latest
        