name: Example workflow using Snyk
on: [ push, workflow_dispatch ]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # - name: Setup Java
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 11
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
