name: trigger the next pipeline

on:
  push:
    branches: [ master ]

jobs:
  Tag-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          git --version
          git config user.name "jstan-isch"
          git config user.email "stanleyikegwuonu@gmail.com"
          git status
          echo -e "\n Deleting previous QA tag"
          #git log --pretty=online QA...HEAD > log.txt
          git tag
          #git tag -d QA
          #echo -e "\n DONE"
          #echo -e "\n Push tags to master"
          #git push origin :refs/tags/QA
          #echo -e "\n DONE"
          #echo -e "\n Creating new QA tag to HEAD"
          #git tag -a QA -F log.txt
          #echo -e "\n DONE"
          #echo -e "\n Push tags to master"
          #git rev-list -n 1 QA
          #echo -e "\n DONE"
          #echo -e "\n Job Completed"
          
      
      
  
