name: Test Deployment

on:
  push:
    branches:
      - master
      
jobs:
  see-the-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
      - name: github-context
        run: echo '${{ toJSON(github) }}'
      - name: get-the-current-commit
        run: "echo previous commit: $(git rev-list -n2 master | tail -n1)"
      - name: get-the-previous-commit
        run: "echo current commit: $(git rev-list -n1 master)"
    
