name: Version Build

on:
  workflow_dispatch:
  #push:
    #branches: master

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        persist-credentials: true
        #token: ${{ secrets.MY_PAT }}
    - name: git
      run: |
        ${{ github.workspace }}/CI/scripts/validate_yaml
        echo "::error validate_yaml::Missing Value"
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git --version
        git config user.name "jstan-isch"
        git config user.email "stanleyikegwuonu@gmail.com"
        git status
        git tag
        git describe
        echo -e "\n Deleting previous QA tag"
        git log QA...HEAD > log.txt
        git tag -d QA
        echo -e "\n DONE"
        echo -e "\n Push tags to master"
        git push origin :refs/tags/QA
        echo -e "\n DONE"
        echo -e "\n Creating new QA tag to HEAD"
        git tag -a QA -F log.txt
        echo -e "\n DONE"
        echo -e "\n Push tags to master"
        git rev-list -n 1 QA
        git push origin QA
        echo -e "\n DONE"
        echo -e "\n Job Completed"
