name: Test Deploy

on:
  pull_request:
    branches:
      - master
      
jobs:
  see-the-contexts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout pull request HEAD
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.MY_PAT }}
          
      - name: Create a file
        run: |
          touch file8.txt
          echo "added dummy file 6" > file8.txt
          
      - name: commit and push
        run: |
          git config user.name jstan-isch
          git config user.email stanleyikegwuonu@gmail.com
          git add .
          git commit -m "generated"
          git push
      
      - name: Repository Dispatch
        run: |
          curl \
          -H "Authorization: Bearer ${{ secrets.MY_PAT }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/dispatches" \
          -d '{
            "event_type": "Success", 
            "client_payload": {"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "test": "test message"}}'
      
#       - name: Repository Dispatch
#         uses: peter-evans/repository-dispatch@v1
#         with:
#           token: ${{ secrets.MY_PAT }}
#           event-type: my-event
#           client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "test": "test message"}'   
