name: Test Deployment

on:
  pull_request:
    branches:
      - master
      
jobs:
  see-the-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
      - name: github-context
        run: echo '${{ toJSON(github) }}'
      - name: get-the-current-commit
        run: echo ${{ github.event.after }}
      - name: get-the-previous-commit
        run: echo '${{ toJSON(github.event.before) }}'
    
