name: Test Deployment

on:
  push:
    branches:
      - master
      
jobs:
  see-the-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: github-context
        run: echo '${{ toJSON(github) }}'
      - name: get-the-previous-commit
        run: echo $(git rev-list -n 1)
    
