name: Test Deployment

on:
  push:
    branches:
      - master
      
jobs:
  Build:
    runs-on: ubuntu_latest
    environment:
      name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3  
      - name: Build
        run: echo "Building..."
  
  Test:
    runs-on: ubuntu_latest
    environment:
      name: Build
    steps:
      - name: Test
        run: echo "Testing..."
  
  Deploy:
    runs-on: ubuntu_latest
    environment:
      name: Build

    steps:  
      - name: Deploy
        run: echo "Deploying..."
