name: Test Deploy

on:
  pull_request:
    branches: 
      - master
    paths:
      - 'sre-spec.y*ml'
      
jobs:
  see-the-contexts:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      credentials: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    steps:
      - name: Checkout PR HEAD
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
#           token: ${{ secrets.MY_PAT }}
     
      - name: install curl
        run: apk --no-cache add curl
        
      - name: Update file
        run: |
          echo "added dummy file 6" >> file28.txt
          
      - name: commit and push 1
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes found"
            git config user.name jstan-isch
            git config user.email stanleyikegwuonu@gmail.com
            git add .
            git commit -m "generated"
            git push
          else
            echo "No changes found, exiting."
            echo "Job Completed!"
          
          
  tee-the-contexts:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      credentials: 
        username: ${{ DOCKERHUB_USERNAME }}
        password: ${{ DOCKERHUB_TOKEN }}
    
    steps:
      - name: Checkout PR HEAD
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
#           token: ${{ secrets.MY_PAT }}
          
      - name: Update file
        run: |
          echo "added dummy file 6" >> Jenkinsfile_main
          
      - name: commit and push 2
        run: |
          run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes found"
            git config user.name jstan-isch
            git config user.email stanleyikegwuonu@gmail.com
            git add .
            git commit -m "generated"
            git push
          else
            echo "No changes found, exiting."
            echo "Job Completed!"
     
  vee-the-contexts:
    needs: [see-the-contexts, tee-the-contexts]
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        run: |
          curl \
          -H "Authorization: Bearer ${{ secrets.MY_PAT }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/dispatches" \
          -d '{
            "event_type": "Success", 
            "client_payload": {"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "test": "test message"}}'
      
#       - name: Repository Dispatch
#         uses: peter-evans/repository-dispatch@v1
#         with:
#           token: ${{ secrets.MY_PAT }}
#           event-type: my-event
#           client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "test": "test message"}'   
