# https://github.com/marketplace/actions/xray-action

- name: xray-action
uses: mikepenz/xray-action@v3


- name: "Import results to Xray"
  uses: mikepenz/xray-action@{latest-release}
  with:
    username: ${{ secrets.XRAY_CLIENT_ID }}
    password: ${{ secrets.XRAY_CLIENT_SECRET }}
    testFormat: "junit"
    testPaths: "**/test/*.xml"
    testExecKey: "TEST-1"
    projectKey: "TEST"